<?php

namespace Tests\Feature;

use App\Events\NewEntryRegisterEvent;
use App\Mail\WelcomeNewEntryMail;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Mail;
use Tests\TestCase;

class EntryTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Mail::fake();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_an_email_can_be_enter_contest()
    {
//        $this->withoutExceptionHandling();
        $response = $this->post('/contest', [
            'email' => 'test@gmail.com'
        ]);
        $this->assertDatabaseCount('contest_entries', 1);
        $response->assertStatus(200);
    }

    public function testEmailIsRequired(){
//        $this->withoutExceptionHandling();
        $response = $this->post('/contest', [
            'email' => ''
        ]);
        $this->assertDatabaseCount('contest_entries', 0);
        $response->assertStatus(302);
    }

    public function testEmailIs(){
//        $this->withoutExceptionHandling();
        $response = $this->post('/contest', [
            'email' => 'sdasd'
        ]);
        $this->assertDatabaseCount('contest_entries', 0);
        $response->assertStatus(302);
    }

    public function testEntryRegisterWasDispatch(){
        Event::fake([NewEntryRegisterEvent::class]);
        $response = $this->post('/contest', [
            'email' => 'huy@gmail.com'
        ]);
        Event::assertDispatched(NewEntryRegisterEvent::class);
    }

    public function testSendWelcomeNotification(){
        $this->withoutExceptionHandling();
        $response = $this->post('/contest', [
            'email' => 'huy@gmail.com'
        ]);
        Mail::assertQueued(WelcomeNewEntryMail::class);
//        Event::assertDispatched(NewEntryRegisterEvent::class);
    }
}
